---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ cookiecutter.project_name.lower() }}
  namespace: {{ cookiecutter.project_name.lower() }} 
spec:
  forProvider:
    locationConstraint: us-east-1
    acl: private
    tagging:
      tagSet:
{%- for key, value in cookiecutter.tags|dictsort %}
        - key: {{ key }}
          value: {{ value }}
{%- endfor -%}
